# Generated by Django 4.0.3 on 2022-03-27 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='tast',
            new_name='task',
        ),
    ]
